<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE documentos [
    <!ELEMENT documentos (libros, revistas, periodicos)>
    <!-- Libros -->
    <!ELEMENT libros (libro*)>
    <!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
    <!ATTLIST libro
        id ID #REQUIRED
        tipo_clase (novela | infantil | didactico) #REQUIRED
        num_paginas CDATA #REQUIRED
    >       
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT capitulos (capitulo+)>
    <!ELEMENT capitulo (titulo, contenido)>
    <!ATTLIST capitulo num_paginas CDATA #REQUIRED>
    <!ELEMENT contenido EMPTY>
    <!ATTLIST contenido info CDATA #REQUIRED>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
    <!-- Revistas -->
    <!ELEMENT revistas (revista*)>
    <!ELEMENT revista (titulo, numero, indice, secciones_r)>
    <!ATTLIST revista
        id ID #REQUIRED
        tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED
        num_paginas CDATA #REQUIRED
    >
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT secciones_r (seccion_r+)>
    <!ELEMENT seccion_r (contenido)>
    <!ATTLIST seccion_r num_paginas CDATA #IREQUIRED>
    <!-- Periodicos -->
    <!ELEMENT periodicos (periodico*)>
    <!ELEMENT periodico (secciones_p+, indice)>
    <!ATTLIST periodico
        id ID #REQUIRED
        tipo_clase (nacional | internacional) #REQUIRED
        fecha CDATA #REQUIRED
    >
    <!ELEMENT secciones_p (seccion_p+)>
    <!ELEMENT seccion_p (articulo+)>
    <!ATTLIST seccion_p tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
    <!ELEMENT articulo (contenido)>
    <!ATTLIST articulo autor CDATA #IMPLIED>
    
]>

<documentos>
<!-- Libros -->
    <libros>
        <libro id="L0001" tipo_clase="novela" num_paginas="358">
            <titulo>Caballos desbocados</titulo>
            <capitulos>
                <capitulo num_paginas="3">
                    <titulo>Capítulo 1</titulo>
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </capitulo>
                <capitulo num_paginas="5">
                    <titulo>Capítulo 2</titulo>
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </capitulo>
            </capitulos>
            <indice>Aquí va el índice</indice>
            <sinopsis>Esta novela constituye la clave para comprender el pensamiento y la posición personal 
            del autor ante la vida y el mundo. A través del hilo de la narración y de la rebeldía de unos 
            protagonistas jóvenes que aspiran a una especie de pureza utópica, vamos desgranando las causas 
            que llevaron a Mishima a su suicidio ritual.</sinopsis>
        </libro>
    </libros>    
<!-- Revistas -->
    <revistas>
        <revista id="R" tipo_clase="otras" num_paginas="18">
            <titulo>White Dwarf</titulo>
            <numero>46</numero>
            <indice>Aquí va el índice</indice>
            <secciones_r>
                <seccion_r num_paginas="7">
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </seccion_r>
                <seccion_r num_paginas="1">
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </seccion_r>
        </revista>
    </revistas>
<!-- Periodicos -->
    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha="2023-05-06">
            <secciones_p>
                <seccion_p tipo_seccion="nacional">
                    <articulo autor="Chiquito de la Calzada">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                    <articulo autor="Eugenio">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                </seccion_p>
                <seccion_p tipo_seccion="economica">
                    <articulo autor="El Dioni">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>

                    <articulo autor="Ruiz-Mateos">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                </seccion_p>
            </secciones_p>
            <indice></indice>
        </periodico>
    </periodicos>
</documentos>