<?xml version="1.0" encoding="UTF-8"?>

<!-- Propuesta de Manuel Sanchis Tormo -->

<!DOCTYPE documentos [
    <!-- Debido a las limitaciones de XML y ante la imposibilidad de poder repetir el nombre de un elemento
    he optado por utlizar pipe en la definicion del contenido del elemento "seccion":
    
    <!ELEMENT seccion (contenido | articulo+)>

    Debido a las limitaciones de XML y ante la imposibilidad de poder repetir el nombre de un elemento
    he optado por utlizar #IMPLIED en definicion de los atributos del elemento "seccion":
    
    <!ATTLIST seccion
        num_paginas CDATA #IMPLIED
        tipo_seccion (economica | opinion | deportes | nacional | internacional) #IMPLIED
    > 
    
    De esta forma el documento se valida y se cumplen los requisitos del enunciado a la hora de nombrar los elementos
    del archivo XML sin embargo esto puede generar confusion ya que el archivo DTD validaria algunas 
    estructuras XML que no cumplen con los requisitos del enunciado como por ejemplo:

    <revistas>
        <revista id="R" tipo_clase="" num_paginas="">
            <titulo></titulo>
            <numero></numero>
            <indice></indice>
            <secciones>
                <seccion tipo_seccion="">
                    <articulo autor="">
                        <contenido info=""/>  
                    </articulo>
                </seccion>
            </secciones>
        </revista>
    </revistas> 
    
    Para evitar esto he realizado otra propuesta (ver ae2_xml_dtd_v2) a costa de no cumplir los requisitos del enunciado 
    a la hora de nombrar los elementos del archivo XML.
    
    La conclusion a la que he llegado es que es imposible validar este archico XML usando DTD cumpliendo con los 
    requisitos del enunciado. -->

    <!ELEMENT documentos (libros, revistas, periodicos)>
    <!-- Libros -->
    <!ELEMENT libros (libro*)>
    <!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
    <!ATTLIST libro
        id ID #REQUIRED
        tipo_clase (novela | infantil | didactico) #REQUIRED
        num_paginas CDATA #REQUIRED
    >       
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT capitulos (capitulo+)>
    <!ELEMENT capitulo (titulo, contenido)>
    <!ATTLIST capitulo num_paginas CDATA #REQUIRED>
    <!ELEMENT contenido EMPTY>
    <!ATTLIST contenido info CDATA #REQUIRED>
    <!ELEMENT indice (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
    <!-- Revistas -->
    <!ELEMENT revistas (revista*)>
    <!ELEMENT revista (titulo, numero, indice, secciones)>
    <!ATTLIST revista
        id ID #REQUIRED
        tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED
        num_paginas CDATA #REQUIRED
    >
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT secciones (seccion+)>
    <!ELEMENT seccion (contenido | articulo+)>
    <!ATTLIST seccion
        num_paginas CDATA #IMPLIED
        tipo_seccion (economica | opinion | deportes | nacional | internacional) #IMPLIED
    >
    <!-- Periodicos -->
    <!ELEMENT periodicos (periodico*)>
    <!ELEMENT periodico (secciones+, indice)>
    <!ATTLIST periodico
        id ID #REQUIRED
        tipo_clase (nacional | internacional) #REQUIRED
        fecha CDATA #REQUIRED
    >
    <!ELEMENT articulo (contenido)>
    <!ATTLIST articulo autor CDATA #IMPLIED>
]>

<documentos>
<!-- Libros -->
    <libros>
        <libro id="L0001" tipo_clase="novela" num_paginas="358">
            <titulo>Caballos desbocados</titulo>
            <capitulos>
                <capitulo num_paginas="3">
                    <titulo>Capítulo 1</titulo>
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </capitulo>
                <capitulo num_paginas="5">
                    <titulo>Capítulo 2</titulo>
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </capitulo>
            </capitulos>
            <indice>Aquí va el índice</indice>
            <sinopsis>Esta novela constituye la clave para comprender el pensamiento y la posición personal 
            del autor ante la vida y el mundo. A través del hilo de la narración y de la rebeldía de unos 
            protagonistas jóvenes que aspiran a una especie de pureza utópica, vamos desgranando las causas 
            que llevaron a Mishima a su suicidio ritual.</sinopsis>
        </libro>
    </libros>
<!-- Revistas -->
    <revistas>
        <revista id="R" tipo_clase="otras" num_paginas="78">
            <titulo>White Dwarf</titulo>
            <numero>46</numero>
            <indice>Aquí va el índice</indice>
            <secciones>
                <seccion num_paginas="7">
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </seccion>
                <seccion num_paginas="1">
                    <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>
                </seccion>
            </secciones>
        </revista>
    </revistas>
<!-- Periodicos -->
    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha="2023-05-06">
            <secciones>
                <seccion tipo_seccion="nacional">
                    <articulo autor="Chiquito de la Calzada">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                    <articulo autor="Eugenio">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                </seccion>
                <seccion tipo_seccion="economica">
                    <articulo autor="El Dioni">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                    <articulo autor="Ruiz-Mateos">
                        <contenido info="https://www.youtube.com/watch?v=HEI55-gQ0fQ"/>  
                    </articulo>
                </seccion>
            </secciones>
            <indice></indice>
        </periodico>
    </periodicos>
</documentos>